----
title: "Hierarchical beta binomial"
author: "Steve Simon"
date: "Saturday, May 28, 2016"
output: html_document
---

Assume that you have two "clusters". The first is your prior data 
with 4/16 successes/failures and the second is your observed data with
18/42 successes/failures.

Now consider the same prior, but your observed data is 54/6 successes/failures.

I'm still working on thse sections.

```{r, compute_everything_gamma_gamma, eval=TRUE}
rm(list=ls())

calculate_gamma_gamma_prior <- function(s0, s1, n) {
  gamma_seq <- seq(s0, s1, length=n)
  beta_seq <- seq(1/(n+1), n/(n+1), length=n)
  z <- array(NA, rep(n,4))
  for (i1 in 1:n) {
    for (i2 in 1:n) {
      for (j1 in 1:n) {
        for (j2 in 1:n) {
          z[i1,i2,j1,j2] <-
            dgamma(gamma_seq[i1], 1) *
            dgamma(gamma_seq[i2], 1) *
            dbeta(beta_seq[j1], 1+gamma_seq[i1], 1+gamma_seq[i2]) *
            dbeta(beta_seq[j2], 1+gamma_seq[i1], 1+gamma_seq[i2])
        }
      }
    }
  }
  cat("\n\nSum = ", round(sum(z),2), ".\n\n")
  z <- z / sum(z)
  a <- list(x1=gamma_seq, x2=gamma_seq, x3=beta_seq, x4=beta_seq, z=z)
  return(a)
}
tst1 <- calculate_gamma_gamma_prior(0.1, 10, 15)

calculate_likelihood <- function(x, n, prior, di) {
  d <- dim(prior$z)
  z <- dbinom(x, n, prior[[di]])
  a <- 
    list (x1=rep(1, d[1]), 
          x2=rep(1, d[2]),
          x3=rep(1, d[3]),
          x4=rep(1, d[4]))
  a[[di]] <- z                       
  return(a)
}
tst2 <- calculate_likelihood( 4, 20, tst1, 3)
tst3 <- calculate_likelihood(54, 60, tst1, 4)

calculate_posterior <- function(prior, li) {
  a <- prior
  a[["z"]] <- prior$z*outer(outer(outer(li$x1, li$x2), li$x3), li$x4)
  return(a)
}
tst4 <- calculate_posterior(tst1, tst2)
tst5 <- calculate_posterior(tst1, tst3)

gamma_gamma_prior <- calculate_gamma_gamma_prior(0.1, 10, 29)
prior_likelihood <- calculate_likelihood(4, 20, gamma_gamma_prior, 3)
nice_likelihood  <- calculate_likelihood(18, 60, gamma_gamma_prior, 4)
nasty_likelihood <- calculate_likelihood(54, 60, gamma_gamma_prior,4)
partial_posterior <- calculate_posterior(gamma_gamma_prior, prior_likelihood)
nice_posterior <- calculate_posterior(partial_posterior, nice_likelihood)
nasty_posterior <- calculate_posterior(partial_posterior, nasty_likelihood)

```

Plot everything.

```{r plot_everything_gamma_gamma, fig.width=5, fig.height=5}

draw_surface <- function(d1, d2, a) {
  persp(x=a[[d1]], y=a[[d2]], z=apply(a[["z"]], c(d1,d2), sum), theta=40, phi=20)
  contour(x=a[[d1]], y=a[[d2]], z=apply(a[["z"]], c(d1,d2), sum))
}

draw_surface(1, 2, gamma_gamma_prior)
draw_surface(3, 4, gamma_gamma_prior)
draw_surface(1, 2, partial_posterior)
draw_surface(3, 4, partial_posterior)
draw_surface(1, 2, nice_posterior)
draw_surface(3, 4, nice_posterior)
draw_surface(1, 2, nasty_posterior)
draw_surface(3, 4, nasty_posterior)
```

```{r, compute_everything_beta_gamma}

calculate_beta_gamma_prior <- function(g0, g1, ng, nb) {
  gamma_seq <- seq(g0, g1, length=ng)
  beta_seq <- seq(1/(nb+1), nb/(nb+1), length=nb)
  z <- array(NA, c(nb,ng, nb, nb))
  for (i1 in 1:nb) {
    for (i2 in 1:ng) {
      for (j1 in 1:nb) {
        for (j2 in 1:nb) {
          alpha_h <- gamma_seq[i2]*beta_seq[i1]
          beta_h  <- gamma_seq[i2]*(1-beta_seq[i1])
          z[i1,i2,j1,j2] <-
            dbeta(beta_seq[i1], 1, 1) *
            dgamma(gamma_seq[i2], 2) *
            dbeta(beta_seq[j1], 1+gamma_seq[i1], 1+gamma_seq[i2]) *
            dbeta(beta_seq[j2], 1+gamma_seq[i1], 1+gamma_seq[i2])
        }
      }
    }
  }
  cat("\n\nSum = ", round(sum(z),2), ".\n\n")
  z <- z / sum(z)
  a <- list(x1=beta_seq, x2=gamma_seq, x3=beta_seq, x4=beta_seq, z=z)
  return(a)
}
tst1 <- calculate_beta_gamma_prior(0.1, 20, 50, 15)
tst2 <- calculate_likelihood( 4, 20, tst1, 3)
tst3 <- calculate_posterior(tst1, tst2)
tst4 <- calculate_likelihood(54, 60, tst1, 4)
tst5 <- calculate_posterior(tst3, tst4)

beta_gamma_prior <- calculate_beta_gamma_prior(0.1, 20, 50, 15)
prior_likelihood <- calculate_likelihood(4, 20, beta_gamma_prior, 3)
nice_likelihood  <- calculate_likelihood(18, 60, beta_gamma_prior, 4)
nasty_likelihood <- calculate_likelihood(54, 60, beta_gamma_prior,4)
partial_posterior <- calculate_posterior(beta_gamma_prior, prior_likelihood)
nice_posterior <- calculate_posterior(partial_posterior, nice_likelihood)
nasty_posterior <- calculate_posterior(partial_posterior, nasty_likelihood)
```

```{r plot_everything_beta_gamma, fig.width=5, fig.height=5}
draw_surface(1, 2, beta_gamma_prior)
draw_surface(3, 4, beta_gamma_prior)
draw_surface(1, 2, partial_posterior)
draw_surface(3, 4, partial_posterior)
draw_surface(1, 2, nice_posterior)
draw_surface(3, 4, nice_posterior)
draw_surface(1, 2, nasty_posterior)
draw_surface(3, 4, nasty_posterior)
```


```{r save_everything}
save.image("hierarchical-prior.RData")
```